### ISSUE TITLE
Add Ticker Parser default behavior settings

### ISSUE THREAD

**Issue by MaliciousUpload** [alphabotsystem/Alpha#24]
While Alpha is mainly a crypto related bot having the ability to use using a quick look up for some non-crypto related assets with a shortened tickerid brings up some annoying tickers if you are not looking for crypto related assets. I propose we consider removing it to ensure we cater to all asset classes equally and have the biggest range appeal.

**Comment by MaticConradi** [comment]
The issue is how. There is no way to determine which ticker the user wants to request. There needs to be some form of parsing as completely removing that would render all crypto tickets impossible to get to if you don’t know the exact name. Most if not all users only request coin tickers and not market pair. How would we go around it then?

**Comment by MaticConradi** [comment]
An option to select preferred ticker processing will be added in the future

**Comment by MaticConradi** [comment]
Added
